### ISSUE TITLE
markup calculations missing

### ISSUE THREAD

**Issue by mcn1970** [Mark-Tomlinson/markup-by-attribute-for-woocommerce#11]
wordpress 5.3.2 + woocomerce 5.9

on woocommerce/settings/product there are no options for markup calculations 
![Opera Snapshot_2020-01-29_154050_www tuestifrumoasa ro](https://user-images.githubusercontent.com/29046886/73361618-f2e39d00-42ad-11ea-8aad-72d0422fdab8.png)

**Comment by mcn1970** [comment]
![Untitled-1](https://user-images.githubusercontent.com/29046886/73361817-5f5e9c00-42ae-11ea-943c-d1f6be327b30.jpg)

**Comment by Mark-Tomlinson** [comment]
I'm not entirely sure what you are asking. Markup by Attribute _only_ adds (or subtracts) a markup to product variations based on the attribute options chosen. See the 'Markup (or markdown)' field at the bottom of the attribute pages. There are other plugins that provide more complex, conditional calculations which may be more suitable for your purposes.

Does that answer your question?

![Screenshot 2018-08-31 18 46 32](https://user-images.githubusercontent.com/14809884/73362898-4eda0180-426d-11ea-90ce-686285258d91.png)

**Comment by mcn1970** [comment]
check attachment.
![Untitled-2](https://user-images.githubusercontent.com/29046886/73379266-a0fd4000-42ca-11ea-80bd-4956b8397f1c.jpg)
Markup calculation section doesnt appear in settings area on woocommerce/products/markup so I cannot use sale price for markup

**Comment by Mark-Tomlinson** [comment]
Oh, crap. No wonder I was confused. That was a feature that was built in, then added as an option, then removed completely. I removed it from the written instructions, but failed to update the image of the settings page.

The problem was that this setting had a tendency to create confusion with your customers since the drop-down box would say that we added or subtracted an amount calculated on the regular price, but the sale price would add or subtract a smaller markup. For instance, take a $25.00 item on sale for $15.00 with a 10% discount for yellow. The dropdown box will say “Yellow (-$2.50)” and the description will say “Subtract $2.50 for Yellow”. But we will only subtract $1.50 (10% of $15.00). People notice these things.

Of course, I could make it rewrite the dropdown box and description when the sale ends. But then Markup by Attribute would have to parse through all the variations and rewrite the dropdown boxes and descriptions, which causes system timeouts in my testing.

So, for now anyway, it can only calculate a percentage markup based on the regular price. Sorry about that. I will continue to work toward bringing this feature back.

**Comment by mcn1970** [comment]
now I understand.
but I have another issues which may be related with this plugin.
Please check 
https://www.rochiiceremonie.ro/index.php/product/rochie-de-ceremonie-accoleia/

If you choose marime 46 (in english is size) you will get the page as in screenshoot.
![Opera Snapshot_2020-02-03_213850_www rochiiceremonie ro](https://user-images.githubusercontent.com/29046886/73684982-f3c16800-46cd-11ea-851f-d6edca01db00.png)
I noticed that prices rendered by the plugin are 1.055 lei 955 lei but they have different size and format than standard woocommerce fonts of the theme.
Looking at the page source I couldnt find any explanation.

Does you plugin somehow modify theme's CSS?

**Comment by Mark-Tomlinson** [comment]
No, I don't change any CSS.

I did an inspection of the price information on your page and found that your theme, OceanWP, changes the `<del>...</del>` and `<ins>...</ins>` tags that WooCommerce brackets around the prices. It appears to set the font-size for `<del>` to 25px and the font-size for `<ins>` to 14px. I uninstalled my plugin from my testing site, installed OceanWP theme, and recreated the problem exactly.

![Screenshot 2020-02-03 18 27 17](https://user-images.githubusercontent.com/14809884/73704337-4e4fc980-46b8-11ea-8e43-20ee022ae105.png)

Since OceanWP seems to be a very comprehensive theme with a lot of flexibility, you may want to see if there is a place you can adjust those font sizes.
