### ISSUE TITLE
Percentage does not stack with other attributes

### ISSUE THREAD

**Issue by kylemadkins** [Mark-Tomlinson/markup-by-attribute-for-woocommerce#19]
I was wondering if there's a way for a percentage markup to stack with other marked up attributes. For example, I have a bookcase that adds $50 if you select the 72" option. There's also the option to add a Blackberry wood stain for a 5% up-charge. The base price (regular price) of the bookcase is $200. If I select the 72" option and the Blackberry stain, it adds $50 but it applies the 5% to the base price ($200) instead of the total marked up price ($250). Hope that makes sense

**Comment by Mark-Tomlinson** [comment]
No. I've considered that in the past, but it became complicated. I realized I'd have to add a prioritization field to the attributes, so they could be processed in a certain order--or against the base price only. But, then the plugin would have to sort all the attributes by their prioritization before pricing the variations, which will add processing time to an already long process. Additionally, I'd have to add error-checking so that no attributes have the same priority, lest there be a conflict during pricing.

So, at this point anyway, I have no plans to add that. Sorry.

**Comment by kylemadkins** [comment]
That makes sense. Thank you for the quick response!
